### ISSUE TITLE
軽量化

### ISSUE THREAD

**Issue by ronge-0716** [ronge-0716/Rbot-js#1]
**軽量化**
glitchのころと比べてVScodeだと重くなってしまっています。
pingを100台にはしたいです。

**Comment by daima3629** [comment]
今回のケースではは処理の早さの問題ではなく、回線速度の問題です。
なので回線速度を早めるしかないですね。
PCをLANケーブルで繋ぐとpingは少し早くなると思います。
また、コマンドプロンプトから直接実行するのもひとつの手です。

**Comment by ronge-0716** [comment]
ほうほう……的確なアドバイスありがとうございます！
